sonar.projectKey=WilliamRochaJR_pay-flow
sonar.organization=williamrochajr
sonar.projectName=PayFlow
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test,frontend/src,frontend/e2e
sonar.test.inclusions=backend/src/test/**,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/e2e/**
sonar.exclusions=frontend/dist/**,frontend/coverage/**,frontend/playwright-report/**,frontend/test-results/**

sonar.java.binaries=backend/target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.tsconfigPaths=frontend/tsconfig.app.json
